version: "3.3"

services:
  postgres:
    container_name: ci4_database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/usr/data
      - ./docker/postgre/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  server:
    container_name: 'ci4-server'
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        uid: 1000
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  data:
  src:
