#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#cores
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

COMMIT_MESSAGE=$(cat "$1")

# Verificar se a mensagem de commit contém as tags semânticas com dois pontos
SEMANTIC_TAGS=("docs:" "feat:" "fix:" "perf:" "test:" "refactor:" "style:" "build:" "ci:" "chore:" "revert:" "Merge")

for TAG in "${SEMANTIC_TAGS[@]}"; do
  if [[ $COMMIT_MESSAGE == *"$TAG"* ]]; then

    echo "$COMMIT_MESSAGE" >$1
    exit 0
  fi
done

echo -e "${BRed}ERRO: A mensagem de commit não contém nenhuma das tags semânticas com os dois pontos (docs:, feat:, fix:, perf:, test:, refactor:, style:, build:, ci:, chore:, revert:)${NC}"
exit 1
